PERIPHERALS = spi pwm pit adc #ledtape
DRIVERS = pacer usb_serial nrf24 panic 
SRC = racer.c

# Use low level of optimisation to simplify debugging
OPT = -O1

BOARD = racer

include ../../boards/board.mk
