PERIPHERALS = spi pwm pit adc 
DRIVERS = pacer usb_serial nrf24 panic ledtape
SRC = racer.c

# Use low level of optimisation to simplify debugging
OPT = -O1

BOARD = racer

include ../../boards/board.mk
