PERIPHERALS = pwm pit adc
DRIVERS = usb_serial adxl345 nrf24 pacer panic ledtape

SRC = hat.c

# Use low level of optimisation to simplify debugging
OPT = -O1

BOARD = hat

include ../../boards/board.mk
